# Generated by Django 6.0.5 on 2026-05-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanHo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ch', models.CharField(max_length=200)),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mo_ta', models.TextField(blank=True)),
                ('loai_phong', models.CharField(choices=[('PHONG_TRO', 'Phòng trọ'), ('CAN_HO', 'Căn hộ dịch vụ'), ('DU_AN', 'Dự án')], default='PHONG_TRO', max_length=20)),
                ('trang_thai', models.CharField(choices=[('TRONG', 'Còn trống'), ('CHO_DUYET', 'Chờ duyệt'), ('DA_THUE', 'Đã thuê')], default='TRONG', max_length=20)),
                ('dien_tich', models.FloatField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Căn Hộ / Phòng Trọ',
                'verbose_name_plural': 'Căn Hộ / Phòng Trọ',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='ChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cm', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-building', max_length=50)),
            ],
            options={
                'verbose_name': 'Chuyên Mục',
                'verbose_name_plural': 'Chuyên Mục',
            },
        ),
        migrations.CreateModel(
            name='Anh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_anh', models.URLField(max_length=500)),
                ('la_anh_chinh', models.BooleanField(default=False)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh_set', to='core.canho')),
            ],
            options={
                'verbose_name': 'Ảnh',
                'verbose_name_plural': 'Ảnh',
            },
        ),
        migrations.AddField(
            model_name='canho',
            name='chuyen_muc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chuyenmuc'),
        ),
        migrations.CreateModel(
            name='DiaChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinh', models.CharField(default='TP Hồ Chí Minh', max_length=100)),
                ('quan', models.CharField(max_length=100)),
                ('dia_chi_cu_the', models.CharField(blank=True, max_length=300)),
                ('can_ho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dia_chi', to='core.canho')),
            ],
            options={
                'verbose_name': 'Địa Chỉ',
                'verbose_name_plural': 'Địa Chỉ',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Nhân Viên',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nhan_vien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nhanvien')),
            ],
            options={
                'verbose_name': 'Khách Hàng',
                'verbose_name_plural': 'Khách Hàng',
            },
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lap', models.DateField()),
                ('tong_tien_thu', models.DecimalField(decimal_places=0, max_digits=12)),
                ('minh_chung', models.URLField(blank=True, max_length=500)),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hop_dong_set', to='core.canho')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.khachhang')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.nhanvien')),
            ],
            options={
                'verbose_name': 'Hợp Đồng',
                'verbose_name_plural': 'Hợp Đồng',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='QuanLy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('chuc_vu', models.CharField(default='Quản lý', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quanly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quản Lý',
                'verbose_name_plural': 'Quản Lý',
            },
        ),
        migrations.AddField(
            model_name='chuyenmuc',
            name='quan_ly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quanly'),
        ),
    ]
