# Generated by Django 6.0.5 on 2026-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canho',
            name='loai_phong',
            field=models.CharField(choices=[('BANCOL', 'Bancol'), ('DUPLEX', 'Duplex')], default='BANCOL', max_length=20),
        ),
    ]
