# Generated by Django 6.0.5 on 2026-05-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_canho_loai_phong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nhanvien'),
        ),
    ]
