# Generated by Django 6.0.5 on 2026-05-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hopdong_nhan_vien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canho',
            name='loai_phong',
            field=models.CharField(choices=[('BANCOL', 'Bancol'), ('DUPLEX', 'Duplex'), ('THUONG', 'Thường')], default='BANCOL', max_length=20),
        ),
    ]
