# Generated by Django 6.0.5 on 2026-05-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_canho_loai_phong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khachhang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NhanVienMKT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvienmkt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân Viên MKT',
                'verbose_name_plural': 'Nhân Viên MKT',
            },
        ),
    ]
