# Generated by Django 6.0.5 on 2026-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_khachhang_user_nhanvienmkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='AlphaHome Bot', max_length=100)),
                ('bot_token', models.CharField(max_length=200)),
                ('chat_id', models.CharField(help_text='Channel: @channelname hoặc numeric ID. Group: -100xxxxxxxxxx', max_length=100)),
                ('api_key', models.CharField(help_text='Secret key n8n dùng để xác thực (Header: X-API-Key)', max_length=64)),
                ('hoat_dong', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cấu Hình Telegram',
                'verbose_name_plural': 'Cấu Hình Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(blank=True, max_length=300)),
                ('noi_dung', models.TextField()),
                ('anh_url', models.URLField(blank=True, max_length=500)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('OK', 'Thành công'), ('FAIL', 'Thất bại')], default='OK', max_length=10)),
                ('loi', models.TextField(blank=True)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch Sử Post Telegram',
                'verbose_name_plural': 'Lịch Sử Post Telegram',
                'ordering': ['-ngay_gui'],
            },
        ),
    ]
